import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <Navbar />
          <main className="min-h-[77.6vh] overflow-hidden"> {children}</main>
          <footer className="text-center p-4 md:p-6 bg-gray-900 text-white">
            © 2023 True Feedback. All rights reserved.
          </footer>
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
